profile: local
data_root: ./data
spark:
  master: "local[*]"
  app_name: "bikeops-local"
  timezone: "UTC"
weather:
  city: "Lille"   # ville cible du fichier weather_raw.csv (pas de colonne 'city' en entrée)
